#!/usr/bin/bash

# Copyright (c) 2022. Huawei Technologies Co.,Ltd.ALL rights reserved.
# This program is licensed under Mulan PSL v2.
# You can use it according to the terms and conditions of the Mulan PSL v2.
#          http://license.coscl.org.cn/MulanPSL2
# THIS PROGRAM IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

# #############################################
# @Author    :   liujingjing
# @Contact   :   liujingjing25812@163.com
# @Date      :   2022/06/30
# @License   :   Mulan PSL v2
# @Desc      :   Test the basic functions of rsyslog
# ############################################

source ${OET_PATH}/libs/locallibs/common_lib.sh

function pre_test() {
    LOG_INFO "Start to prepare the test environment."
    DNF_INSTALL time
    cp -f /etc/resolv.conf /etc/resolv.conf.bak
    echo "; generated by /usr/sbin/dhclient-script
search HWEL-server
nameserver 10.98.48.39.23 " >/etc/resolv.conf
    LOG_INFO "End to prepare the test environment."
}

function run_test() {
    LOG_INFO "Start to run test."
    /usr/bin/time systemctl restart rsyslog 2>&1 | grep 0.0
    CHECK_RESULT $? 0 0 "Start time exceeds 0.1s"
    systemctl status rsyslog | grep running
    CHECK_RESULT $? 0 0 "Service not started"
    LOG_INFO "End to run test."
}

function post_test() {
    LOG_INFO "Start to restore the test environment."
    mv -f /etc/resolv.conf.bak /etc/resolv.conf
    systemctl restart rsyslog
    DNF_REMOVE
    LOG_INFO "End to restore the test environment."
}

main "$@"
